### ISSUE TITLE
add support for Spark 2.4

### ISSUE THREAD

**Issue by lgongmsft** [rstudio/mleap#23]
It seems that the latest mleap R package (0.1.3) only supports Spark of version 2.3 and earlier:

https://github.com/rstudio/mleap/tree/master/inst/java

Is it possible to add support for Spark 2.4 (https://en.wikipedia.org/wiki/Apache_Spark#History)?

Thanks!

**Comment by kevinykuo** [comment]
Let's wait until upstream releases update with https://github.com/combust/mleap/pull/496
